"""empty message

Revision ID: 47568d50355c
Revises: 
Create Date: 2019-04-21 22:52:59.895782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47568d50355c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fzu_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_mark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('good_rate', sa.Float(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('max_s', sa.Float(), nullable=True),
    sa.Column('min_s', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['fzu_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_master', sa.Boolean(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['fzu_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_student_number'), 'user', ['student_number'], unique=True)
    op.create_table('mark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mark', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_rate', sa.Float(), nullable=True),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('class_rank_rate', sa.Float(), nullable=True),
    sa.Column('segment', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['fzu_class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    op.drop_index(op.f('ix_user_student_number'), table_name='user')
    op.drop_table('user')
    op.drop_table('class_mark')
    op.drop_table('fzu_class')
    # ### end Alembic commands ###
